### ISSUE TITLE
Citation in Introduction does not work

### ISSUE THREAD

**Issue by habi** [habi/zmk-tooth-cohort-method-manuscript#3]
We cannot seem to cite https://doi.org/10.1016/0030-4220(84)90085-9, also not with its shortdoi: https://github.com/habi/zmk-tooth-cohort-method-manuscript/commit/f9a54247421978d998daceb38e9704e12580030f

Let's find out why.

**Comment by habi** [comment]
The Jupyter citation in M&Ms also doesn't work: "Jupyter [@doi:10.3233/978-1-61499-649-1-87] "

**Comment by dhimmel** [comment]
Cool manuscript! The first one on teeth I've seen. Feel free to add it to https://manubot.org/catalog/ whenever.

Eventually, pandoc [might support](https://github.com/jgm/pandoc/pull/6373) `@{doi:10.1016/0030-4220(84)90085-9}`.

For now here are your options in manubot:

```markdown
Cite with shortDOI like [@doi:10/f9a5424]

Cite with an alias like [@vertucci].

[@vertucci]: doi:10.1016/0030-4220(84)90085-9
```

**Comment by dhimmel** [comment]
Out of curiosity, do you remember where you found out the shortDOI was `f9a5424` (as opposed to `10/f9a5424`). We don't include `10/` in the shortDOI URLs which might have been the source of the confusion?

**Comment by habi** [comment]
> Cool manuscript! The first one on teeth I've seen.

Thanks!
As I learned working on this, there's quite a bit of work being done with microCT in teeth.,
Here's a page with tons of pretty pictures: http://rootcanalanatomy.blogspot.com

>  Feel free to add it to https://manubot.org/catalog/ whenever.

We plan to submit the paper in the coming days, once it's in bioRxiv and submitted to the journal I'll add the remaining text and images to the repository and then the complete manuscript to the catalog.
Even though we didn't *write* the paper with `manubot`, but I really want to have an open copy of the original work available.

**Comment by habi** [comment]
> Out of curiosity, do you remember where you found out the shortDOI was `f9a5424` (as opposed to `10/f9a5424`). We don't include `10/` in the shortDOI URLs which might have been the source of the confusion?

The shortDOI was found with pasting the long one here http://shortdoi.org, which gave me https://doi.org/c9wr8n.
`f9a5424` is the hash of the git commit I'm referring to 😁 
I didn't read the manual properly, thus I didn't include the `10/` 😕

**Comment by habi** [comment]
> Feel free to add it to https://manubot.org/catalog/ whenever.

@dhimmel: I've just added it, now that we have a bioRxiv DOI: https://github.com/manubot/catalog/pull/36
